import type {
  InvoiceStatus,
  PaymentMethod,
  PaymentStatus,
} from "@prisma/client";

import { prisma } from "./prisma";

/** Billing data-access — hospital-scoped, integer FCFA (D-009, D-011, 09 §5). */

export type CreateInvoiceWithItemsData = {
  hospitalId: string;
  encounterId: string;
  invoiceNumber: string;
  status: InvoiceStatus;
  totalAmount: number;
  items: {
    label: string;
    quantity: number;
    unitAmount: number;
    lineTotal: number;
  }[];
  createdById: string;
};

export function createInvoiceWithItems(data: CreateInvoiceWithItemsData) {
  return prisma.invoice.create({
    data: {
      hospitalId: data.hospitalId,
      encounterId: data.encounterId,
      invoiceNumber: data.invoiceNumber,
      status: data.status,
      totalAmount: data.totalAmount,
      createdById: data.createdById,
      items: {
        create: data.items.map((item) => ({
          hospitalId: data.hospitalId,
          label: item.label,
          quantity: item.quantity,
          unitAmount: item.unitAmount,
          lineTotal: item.lineTotal,
        })),
      },
    },
    include: { items: true },
  });
}

/** A single invoice within a hospital, with items, payments and the patient. Phase 2C also
 *  surfaces the cancellation requests (+ any refund voucher) so the invoice view can show state. */
export function findInvoiceById(hospitalId: string, id: string) {
  return prisma.invoice.findFirst({
    where: { id, hospitalId, deletedAt: null },
    include: {
      items: true,
      payments: { orderBy: { paidAt: "asc" }, include: { cashier: true } },
      encounter: { include: { patient: true } },
      cancellationRequests: {
        orderBy: { createdAt: "desc" },
        include: { refundVoucher: true, requestedBy: true, decidedBy: true },
      },
    },
  });
}

export type CreatePaymentData = {
  hospitalId: string;
  invoiceId: string;
  receiptNumber: string;
  amount: number;
  method: PaymentMethod;
  status: PaymentStatus;
  cashierId: string;
  createdById: string;
};

export function createPayment(data: CreatePaymentData) {
  return prisma.payment.create({ data });
}

export type RecordPaymentTxResult = {
  payment: Awaited<ReturnType<typeof prisma.payment.create>>;
  status: InvoiceStatus;
  paidAfter: number;
  remainingAfter: number;
};

/**
 * Phase 5.1 (F-01) — record a payment ATOMICALLY. One interactive transaction: it locks the invoice row
 * (`SELECT … FOR UPDATE`, hospital-scoped, soft-deleted excluded), re-derives the remaining balance from
 * the AUTHORITATIVE recorded payments *inside the lock*, rejects an amount exceeding it, then creates the
 * payment and updates the invoice status together. This makes concurrent double-payment / overpayment
 * impossible (a stale pre-read can no longer authorise an over-payment) and keeps the payment row and the
 * invoice status consistent. The receipt number is pre-generated by the caller via the atomic sequence;
 * a rare rollback only leaves a harmless numbering gap (same property as invoice numbering).
 */
export function recordPaymentTx(params: {
  hospitalId: string;
  invoiceId: string;
  receiptNumber: string;
  amount: number;
  method: PaymentMethod;
  cashierId: string;
  createdById: string;
}): Promise<RecordPaymentTxResult> {
  const { hospitalId, invoiceId, receiptNumber, amount, method, cashierId, createdById } = params;
  return prisma.$transaction(async (tx) => {
    // Serialise concurrent payments on THIS invoice: a scoped row lock (skips other hospitals + voids).
    const locked = await tx.$queryRaw<{ id: string; totalAmount: number }[]>`
      SELECT "id", "totalAmount" FROM "Invoice"
      WHERE "id" = ${invoiceId} AND "hospitalId" = ${hospitalId} AND "deletedAt" IS NULL
      FOR UPDATE`;
    if (locked.length === 0) throw new Error("Facture introuvable dans cet hôpital.");
    const totalAmount = Number(locked[0].totalAmount);

    // Authoritative paid-so-far (recorded payments only), read UNDER the lock — never a stale pre-read.
    const agg = await tx.payment.aggregate({
      _sum: { amount: true },
      where: { hospitalId, invoiceId, status: "recorded" },
    });
    const paid = agg._sum.amount ?? 0;
    const remaining = totalAmount - paid;
    if (amount <= 0 || amount > remaining) {
      throw new Error("Le solde de la facture a changé — paiement refusé (montant supérieur au solde restant).");
    }

    const payment = await tx.payment.create({
      data: { hospitalId, invoiceId, receiptNumber, amount, method, status: "recorded", cashierId, createdById },
    });

    const paidAfter = paid + amount;
    const status: InvoiceStatus = paidAfter >= totalAmount ? "paid" : "partially_paid";
    await tx.invoice.updateMany({ where: { id: invoiceId, hospitalId }, data: { status } });

    return { payment, status, paidAfter, remainingAfter: totalAmount - paidAfter };
  });
}

export function updateInvoiceStatus(
  hospitalId: string,
  id: string,
  status: InvoiceStatus,
) {
  return prisma.invoice.updateMany({
    where: { id, hospitalId },
    data: { status },
  });
}

/** Set a payment's status (Phase 1A Batch 3 — voiding a receipt; never deletes history). */
export function updatePaymentStatus(
  hospitalId: string,
  id: string,
  status: PaymentStatus,
) {
  return prisma.payment.updateMany({ where: { id, hospitalId }, data: { status } });
}

/** Mark a payment's receipt as printed (idempotent timestamp). */
export function markReceiptPrinted(hospitalId: string, paymentId: string) {
  return prisma.payment.updateMany({
    where: { id: paymentId, hospitalId, printedAt: null },
    data: { printedAt: new Date() },
  });
}

export function findPaymentById(hospitalId: string, id: string) {
  return prisma.payment.findFirst({
    where: { id, hospitalId },
    include: {
      cashier: true,
      invoice: {
        include: {
          items: true,
          encounter: { include: { patient: true } },
        },
      },
    },
  });
}

/**
 * Phase 2G — invoices on an encounter that are NOT yet settled (status not in paid / cancelled), used
 * by the discharge gate. Soft-deleted invoices are excluded. Hospital-scoped.
 */
export function listOpenInvoicesForEncounter(hospitalId: string, encounterId: string) {
  return prisma.invoice.findMany({
    where: {
      hospitalId,
      encounterId,
      deletedAt: null,
      status: { notIn: ["paid", "cancelled"] },
    },
    select: { id: true, invoiceNumber: true, status: true, totalAmount: true },
    orderBy: { createdAt: "asc" },
  });
}
